print : print.c
	$(CC) -fPIE -pie -Wall -o  $@ $^

clean:
	rm -f print

#make CC=/mnt/d/WSL/toolchain/ndk12/arm-linux-androideabi/bin/arm-linux-androideabi-gcc
#make CC=/mnt/d/WSL/toolchain/rk3308_guomei/toolchain-rockchip/bin/aarch64-rockchip-linux-gnu-gcc